### ISSUE TITLE
update feedstock to allow django 4.2

### ISSUE THREAD

**Issue by jacksund** [conda-forge/django-simple-history-feedstock#29]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The current recipe restricts the django dependency to <4.2, but this should be changed to <4.3:
https://github.com/conda-forge/django-simple-history-feedstock/blob/cdd4df19ee89b5b6d64bf4c7feaf7b6d21abf051/recipe/meta.yaml#L25

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by rxm7706** [comment]
Thanks @jacksund - Merged and fixed a couple of minor inconsistencies.
